export const REACT_ELEMENT = Symbol('react.element')
export const REACT_TEXT = Symbol('react-text')
export const REACT_FORWARD_REF = Symbol('react.forward_ref')
export const PLACEMENT = Symbol('PLACEMENT')
export const MOVE = Symbol('MOVE')
export const REACT_CONTEXT = Symbol('react.context')
export const REACT_PROVIDER = Symbol('react.provider')
export const REACT_MEMO = Symbol('react.memo')