export const REACT_ELEMENT = Symbol('react.element')
export const REACT_TEXT = Symbol('react-text')
export const REACT_FORWARD_REF = Symbol('react.forward_ref')
export const PLACEMENT = Symbol('PLACEMENT')
export const MOVE = Symbol('MOVE')